config/routes.rb
Rails.application.routes.draw do

  # home_pages
  root                        'home_pages#index'
  get  '/privacy_policy', to: 'home_pages#privacy_policy'

  # users
  get  '/users/search',     to: 'users#index'
  post '/users/create',     to: 'users#create'
  get  '/users/:id',        to: 'users#show'
  post '/image/:id/update', to: 'users#image'

  # names
  get  '/users/:id/name/create', to: 'names#new'
  post '/users/:id/name/create', to: 'names#create'

  # rooms
  get  '/room',            to: 'rooms#index'
  post '/room/:id/create', to: 'rooms#create'
  get  '/room/:id',        to: 'posts#index'

  # posts
  resources :posts

  # tags
  post '/tag/:id/edit', to: 'tags#edit'

  #sessions
  get    '/session', to: 'sessions#new'
  post   '/session', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name,
    presence: true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user
  before_action :have_not_contact, only: [:show]
  before_action :room_out

  def index
    @rooms = Contact.where(user_id: current_user.id)
    @rooms = @rooms.paginate(page: params[:page])
  end

  def create
    @user = User.find_by(id: params[:id])
    ans = already_contact?(current_user, @user)
    if ans
      redirect_to "/room/#{ ans }"
    else
      @room = Room.create!(
        name: "#{ current_user.name_info } と #{ @user.name_info } のセッション"
      )
      Contact.create!(user_id: current_user.id, room_id: @room.id)
      Contact.create!(user_id: @user.id,        room_id: @room.id)
      redirect_to "/room/#{ @room.id }"
    end
  end

  def already_contact?(c_user, p_user)
    ans = false
    c_cons = Contact.where(user_id: c_user.id)
    p_cons = Contact.where(user_id: p_user.id)
    c_cons.each do |c_con|
      p_cons.each do |p_con|
        c_con.room_id == p_con.room_id ? ans = c_con.room_id : ans = ans
      end
    end
    return ans
  end

  def have_not_contact
    if Contact.find_by(room_id: params[:id], user_id: current_user.id).nil?
      flash[:alert] = "権限がありません"
      redirect_to "/room"
    end
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% provide(:title, "セッション中の相手") %>

<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ルーム名</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <th><%= link_to room.roomname, "room/#{room.room_id}" %></th>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/rooms/show.html.erb
<% provide(:title, @room.name) %>

<section class="chat">
  <h2><%= link_to "コメントを投稿する", new_post_path, remote: true %></h2>
  <div id="post-form"></div>
  <div class="chats-container open" id="posts">
    <%= render @posts %>
  </div>
</section>