config/routes.rb
Rails.application.routes.draw do

  # home_pages
  root                        'home_pages#index'
  get  '/privacy_policy', to: 'home_pages#privacy_policy'

  # users
  get  '/users/search',     to: 'users#index'
  post '/users/create',     to: 'users#create'
  get  '/users/:id',        to: 'users#show'
  post '/image/:id/update', to: 'users#image'

  # names
  get  '/users/:id/name/create', to: 'names#new'
  post '/users/:id/name/create', to: 'names#create'

  # rooms
  get  '/room',            to: 'rooms#index'
  post '/room/:id/create', to: 'rooms#create'
  get  '/room/:id',        to: 'posts#index'

  # posts
  resources :posts

  # tags
  post '/tag/:id/edit', to: 'tags#edit'

  #sessions
  get    '/session', to: 'sessions#new'
  post   '/session', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <% if logged_in? %>
        <%= link_to "Session App", "/users/#{current_user.id}", id: "logo" %>
      <% else %>
        <%= link_to "Session App", root_path, id: "logo" %>
      <% end %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="top-nav">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "プロフィール", "/users/#{current_user.id}" %></li>
          <li><%= link_to "セッション中の相手", "/room" %></li>
          <li><%= link_to "検索", "/users/search" %></li>
        <% else %>
          <li><%= link_to "ホーム", root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", "/session" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_shim.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main class="container">
      <h1 class="jumbotron"><%= main_title( yield(:title) ) %></h1>
      <% flash.each do |message_type, message| %>
        <div class="flash <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
  <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
</html>